### PR TITLE
Fixes Deckimporter

### LINKED ISSUE #38: Text deck import is not working
There is a problem while parsing text decks in ThronesDB.

The `app.ui.on_content_change` function inside _deckimport_ is working fine, but the call to `app.deck.init` is broken.

Since `deck.on_data_loaded` is defined in `app.deck.init` to run only after an 'data.app' event is triggered, the deck is never loaded after parsing. Also, calling `deck.init` at every change to the textarea will bind the `$(document).on('data.app', deck.on_data_loaded);` line multiple times (since jQuery 1.4).

### LINKED ISSUE #61: Copy/paste deck import
When I try to save a deck an error opens saying the deck cannot be saved without a faction, even though I do have a faction.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #61 
refs #38 
refs #215 
refs #218

### CODE REVIEW

File: src/AppBundle/Resources/public/js/ui.deckimport.js [hunk 1]
```diff
@@ -2,27 +2,32 @@
...
+        text.match(/[^\r\n]+/g).forEach(function (token)
         {
-            var qty = 1, name = token.trim(), card;
-            if(token[0] === '(') {
-                return;
-            }
-            if(name.match(/^(\d+)x (.*)/)) {
+            var qty = 1, name = token.trim(), card, packName;
+            if (name.match(/^(\d+)x? ([^(]+) \(([^)]+)\)/)) {
+              qty = parseInt(RegExp.$1, 10);
```
Comment (ystros) [inline src/AppBundle/Resources/public/js/ui.deckimport.js]: The rest of this file is using 4 space indent, while a lot of the new `if`s are using 2 space. However, this may be worth addressing separately by introducing linting rules.

File: src/AppBundle/Resources/public/js/ui.deckimport.js [hunk 2]
```diff
@@ -2,27 +2,32 @@
...
+              name = RegExp.$2.trim();
+              packName = RegExp.$3.trim();
+            } else if(name.match(/^(\d+)x (.*)/)) {
```
Comment (ystros) [inline src/AppBundle/Resources/public/js/ui.deckimport.js]: Should the `x` character here be optional as with above?

File: src/AppBundle/Resources/public/js/ui.deckimport.js (hunk 1 above)
Comment (stopfstedt) [reply src/AppBundle/Resources/public/js/ui.deckimport.js]: will fix. agreed, the code base definitely needs coding standards enforced via phpcs and js/eslint, etc. let's deal with that separately.

Comment (stopfstedt) [reply src/AppBundle/Resources/public/js/ui.deckimport.js]: handled.

File: src/AppBundle/Resources/public/js/ui.deckimport.js (hunk 2 above)
Comment (stopfstedt) [reply src/AppBundle/Resources/public/js/ui.deckimport.js]: corrected.
